# Generated by Django 5.0.4 on 2024-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='commande_ligne',
        ),
        migrations.AddField(
            model_name='facture',
            name='commande_ligne',
            field=models.ManyToManyField(related_name='factures', to='commandes.commande_ligne'),
        ),
    ]
