# Generated by Django 5.0.3 on 2024-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactureVente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facture_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_comptabilisation', models.DateField(blank=True, null=True)),
                ('date_decheance', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
