# Generated by Django 5.0.3 on 2024-04-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures_vente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturevente',
            name='facture_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
