# Generated by Django 5.0.4 on 2024-05-05 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devises', '0002_alter_devise_devise'),
        ('factures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_annule', models.BooleanField(default=False)),
                ('etat', models.CharField(choices=[('complet', 'Complet'), ('partiel', 'Partiel')], default='complet', max_length=20)),
                ('mode_reglement', models.CharField(choices=[('Espèce', 'Espèce'), ('Chèque', 'Chèque'), ('CIB', 'CIB'), ('Avance', 'Avance'), ('Virement', 'Virement')], default='complet', max_length=20)),
                ('commentaire', models.CharField(max_length=255)),
                ('creer_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devises.devise')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factures.facture')),
            ],
        ),
    ]
