# Generated by Django 5.0.3 on 2024-04-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(choices=[('EUR', 'EUR (EUR)'), ('GBP', 'GBP (GBP)'), ('USD', 'USD (USD)')], default='EUR', max_length=10)),
            ],
        ),
    ]
