# Generated by Django 5.0.3 on 2024-04-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_client_dossier_valide_and_more'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('pht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mtva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ttva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_promo', models.BooleanField(default=False)),
                ('code_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
            options={
                'unique_together': {('commande', 'produits')},
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='commandes.Commande_ligne', to='produits.produit'),
        ),
    ]
