# Generated by Django 5.0.3 on 2024-03-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_dossier_valide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='est_vip',
            field=models.BooleanField(default=False),
        ),
    ]
