# Generated by Django 5.0.3 on 2024-04-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_devise'),
        ('devises', '0002_alter_devise_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dossier_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='article_imposition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie_compte',
            field=models.CharField(choices=[('Client', 'Client'), ('Supplier', 'Supplier')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postale',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_tva',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='condition_paiement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='cree_par',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='devise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devises.devise'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='fonction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nature_compte',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='nis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='registre_commerce',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='rue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='secteur_activite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='sigle',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_de_region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
